# Generated by Django 6.0.1 on 2026-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("surname", models.CharField(max_length=150, verbose_name="Отчество")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email", "first_name", "surname", "last_name"],
            },
        ),
    ]
