# Generated by Django 6.0.1 on 2026-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                blank=True, to="newsletter.subscriber", verbose_name="Получатели"
            ),
        ),
    ]
