# Generated by Django 6.0.1 on 2026-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_alter_mailing_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
